//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;
using UnityEngine.Networking;

namespace BlobWars
{
	public class AttackBall : MonoBehaviour
	{
		 Vector3 syncPos;
		Vector3 destination;
		float speed = 5;
		private float minDistance = .01f;
		public AttackBall ()
		{
		}

		public void moveTo(Vector3 location) {
			destination = location;
		}

		private void StepMove () {
			// If the distance is bigger than range, or I just spawned and have to leave the tower.
			if (Vector3.Distance (transform.position, destination) > minDistance) {
				// TODO: PATHFINDING 
				// Do your own pathfinding here
				Vector3 movement = destination - transform.position;
				// Normalise the movement vector and make it proportional to the speed per second.
				movement = movement.normalized * speed * Time.deltaTime;
				// Move the player to it's current position plus the movement.
				transform.position = transform.position + movement;

			
			} else {
				transform.position = GetComponentInParent<Blob>().transform	.position;
			}
			
			
			
		}
		public void Update () {
			StepMove ();
		}

	}
}

